useFMTitle: false
useNoteTitleForLink: true
noLegacyNoteRef: true
mermaid: true
useKatex: true
usePrettyRefs: true
dev:
    enablePreviewV2: true
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    usePrettyRefs: true
    title: Dendron
    description: Personal knowledge space
    siteLastModified: true
    gh_edit_branch: main
    duplicateNoteBehavior:
        action: useVault
        payload:
            - vault
            - wm
version: 3
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: false
            leaveTrace: false
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
    randomNote: {}
workspace:
    vaults:
        -
            fsPath: wm
            remote:
                type: git
                url: 'https://github.com/brainworkup/wm'
            name: wm
        -
            fsPath: vault
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: true
    maxPreviewsCached: 10
    maxNoteLength: 1000000
    enableUserTags: true
    enableHashTags: true
    dendronVersion: 0.65.0
