maxPreviewsCached: 10
vaults:
    - fsPath: wm
      remote:
          type: git
          url: "https://github.com/brainworkup/wm"
      name: wm
    - fsPath: vault
useFMTitle: false
useNoteTitleForLink: true
noAutoCreateOnDefinition: true
noLegacyNoteRef: true
noXVaultWikiLink: true
mermaid: true
useKatex: true
autoFoldFrontmatter: true
usePrettyRefs: true
dev:
    enablePreviewV2: true
journal:
    dailyDomain: daily
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfDomain
    firstDayOfWeek: 1
scratch:
    name: scratch
    dateFormat: y.MM.dd.HHmmss
    addBehavior: asOwnDomain
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    usePrettyRefs: true
    title: Dendron
    description: Personal knowledge space
    siteLastModified: true
    gh_edit_branch: main
    duplicateNoteBehavior:
        action: useVault
        payload:
            - vault
            - wm
version: 1
lookupConfirmVaultOnCreate: false
lookup:
    note:
        selectionType: selectionExtract
        leaveTrace: false
initializeRemoteVaults: true
maxNoteLength: 1000000
