---
title: "ADHD"
subtitle: "Neuropsych Assessment"  
author: 
  - "Joey Trampush"
  - "Ashraf Elmashat"
date: 2021-12-21
output:
  xaringan::moon_reader:
    css: ["xaringan-themer.css", "default"]
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---
class: center

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width = 9, fig.height = 3.5, fig.retina = 3,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  hiline = TRUE,
  fig.showtext = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
# style_mono_accent_inverse(
#   base_color = "#1c5253",
#   header_font_google = google_font("Josefin Sans"),
#   text_font_google   = google_font("Montserrat", "300", "300i"),
#   code_font_google   = google_font("Fira Mono")
# )
```

```{r patient}
patient <- "SL"
```

```{r echo=FALSE}
library(highcharter)
library(tidyverse)
library(htmlwidgets)
library(widgetframe)
```

```{r read-csv}
data_path <- here::here(patient, "csv")
files <- dir(data_path, pattern = "*.csv")
neuropsych <-
  files %>%
  set_names() %>%
  map_df(
    ~ readr::read_csv(file.path(data_path, .), show_col_types = FALSE),
    na = c("", "NA", "--", "-"),
    .id = "filename"
  ) %>%
  filter(!is.na(percentile)) %>%
  distinct() %>%
  mutate(z = qnorm(percentile / 100)) %>%
  mutate(domain = forcats::as_factor(domain)) %>%
  mutate(subdomain = forcats::as_factor(subdomain)) %>%
  mutate(narrow = forcats::as_factor(narrow)) %>%
  mutate(pass = forcats::as_factor(pass)) %>%
  mutate(verbal = forcats::as_factor(verbal)) %>%
  mutate(timed = forcats::as_factor(timed))
```

```{r, make-factors-neurocog}
# Subset neurocognitive data
neurocog <-
  neuropsych %>%
  filter(test_type == "npsych_test")
# domain
neurocog <-
  neurocog %>%
  group_by(domain, .add = TRUE) %>%
  filter(!is.na(percentile)) %>%
  mutate(z_mean_dom = mean(z), z_sd_dom = sd(z)) %>%
  mutate(
    pct_mean_dom = mean(percentile),
    pct_sd_dom = sd(percentile)
  ) %>%
  ungroup()
# subdomain
neurocog <-
  neurocog %>%
  group_by(subdomain, .add = TRUE) %>%
  filter(!is.na(percentile)) %>%
  mutate(z_mean_sub = mean(z), z_sd_sub = sd(z)) %>%
  mutate(
    pct_mean_sub = mean(percentile),
    pct_sd_sub = sd(percentile)
  ) %>%
  ungroup()
# narrow
neurocog <-
  neurocog %>%
  group_by(narrow, .add = TRUE) %>%
  filter(!is.na(percentile)) %>%
  mutate(z_mean_narrow = mean(z), z_sd_narrow = sd(z)) %>%
  mutate(
    pct_mean_narrow = mean(percentile),
    pct_sd_narrow = sd(percentile)
  ) %>%
  ungroup()
# pass
neurocog <-
  neurocog %>%
  group_by(pass, .add = TRUE) %>%
  filter(!is.na(percentile)) %>%
  mutate(z_mean_pass = mean(z), z_sd_pass = sd(z)) %>%
  ungroup()
# verbal
neurocog <-
  neurocog %>%
  group_by(verbal, .add = TRUE) %>%
  filter(!is.na(percentile)) %>%
  mutate(z_mean_verbal = mean(z), z_sd_verbal = sd(z)) %>%
  ungroup()
# timed
neurocog <-
  neurocog %>%
  group_by(timed, .add = TRUE) %>%
  filter(!is.na(percentile)) %>%
  mutate(z_mean_timed = mean(z), z_sd_timed = sd(z)) %>%
  ungroup()
# result text
neurocog <-
  neurocog %>%
  dplyr::mutate(
    result = glue::glue(
      "{patient}'s score on {scale}, a measure of {description}, fell in the *{range}* range (PR = {percentile})."
    )
  )
```

```{r, make-factors-neurobehav}
# Subset neurobehavioral data
neurobehav <-
  neuropsych %>%
  filter(test_type != "npsych_test")
# domain
neurobehav <-
  neurobehav %>%
  group_by(domain, .add = TRUE) %>%
  filter(!is.na(score)) %>%
  mutate(z_mean_dom = mean(z), z_sd_dom = sd(z)) %>%
  mutate(
    pct_mean_dom = mean(percentile),
    pct_sd_dom = sd(percentile)
  ) %>%
  ungroup()
# subdomain
neurobehav <-
  neurobehav %>%
  group_by(subdomain, .add = TRUE) %>%
  filter(!is.na(score)) %>%
  mutate(z_mean_sub = mean(z), z_sd_sub = sd(z)) %>%
  mutate(
    pct_mean_sub = mean(percentile),
    pct_sd_sub = sd(percentile)
  ) %>%
  ungroup()
# narrow
neurobehav <-
  neurobehav %>%
  group_by(narrow, .add = TRUE) %>%
  filter(!is.na(score)) %>%
  mutate(z_mean_narrow = mean(z), z_sd_narrow = sd(z)) %>%
  mutate(
    pct_mean_narrow = mean(percentile),
    pct_sd_narrow = sd(percentile)
  ) %>%
  ungroup()
# result text
neurobehav <-
  neurobehav %>%
  dplyr::mutate(
    result = glue::glue(
      "{patient}'s score on {scale}, a measure of {description}, fell in the *{range}* range (PR = {percentile})."
    )
  )
```

```{r, write-data}
readr::write_csv(neuropsych, here::here(patient, "neuropsych.csv"))
readr::write_csv(neurocog, here::here(patient, "neurocog.csv"))
readr::write_csv(neurobehav, here::here(patient, "neurobehav.csv"))
```

```{r, read-data}
neuropsych <-
  readr::read_csv(here::here(patient, "neuropsych.csv"), show_col_types = FALSE)
neurocog <-
  readr::read_csv(here::here(patient, "neurocog.csv"), show_col_types = FALSE)
neurobehav <-
  readr::read_csv(here::here(patient, "neurobehav.csv"), show_col_types = FALSE)
```

#### Drilldown Highcharter`R`

```{r drilldown-level1}
## Level 1
## Domain scores
# 1. create mean z-scores for domain
ncog1 <- neurocog %>%
  dplyr::group_by(domain) %>%
  dplyr::summarize(zMean = mean(z),
                   zPct = mean(percentile)) %>%
  dplyr::mutate(range = NA)
ncog1$zMean <- round(ncog1$zMean, 2L)
ncog1$zPct <- round(ncog1$zPct, 0L)
ncog1 <-
  ncog1 %>%
  dplyr::mutate(
    range = dplyr::case_when(
      zPct >= 98 ~ "Exceptionally High",
      zPct %in% 91:97 ~ "Above Average",
      zPct %in% 75:90 ~ "High-Average",
      zPct %in% 25:74 ~ "Average",
      zPct %in% 9:24 ~ "Low-Average",
      zPct %in% 2:8 ~ "Below Average",
      zPct < 2 ~ "Exceptionally Low",
      TRUE ~ as.character(range)
    )
  )

# 2. sort hi to lo
ncog1 <- arrange(ncog1, desc(zMean))

# 3. create tibble with new column with domain name lowercase
ncog_level1_status <- tibble(
  name = ncog1$domain,
  y = ncog1$zMean,
  y2 = ncog1$zPct,
  range = ncog1$range,
  drilldown = tolower(name)
)
```

```{r drilldown-level2}
## Level 2
## Subdomain scores
## function to create second level of drilldown (subdomain scores)
ncog_level2_drill <-
  lapply(unique(neurocog$domain), function(x_level) {
    ncog2 <- subset(neurocog, neurocog$domain %in% x_level)
    
    # same as above
    ncog2 <-
      ncog2 %>%
      group_by(subdomain) %>%
      summarize(zMean = mean(z),
                zPct = mean(percentile)) %>%
      mutate(range = NA)
    
    # round z-score to 1 decimal
    ncog2$zMean <- round(ncog2$zMean, 2L)
    ncog2$zPct <- round(ncog2$zPct, 0L)
    ncog2 <-
      ncog2 %>%
      dplyr::mutate(
        range = dplyr::case_when(
          zPct >= 98 ~ "Exceptionally High",
          zPct %in% 91:97 ~ "Above Average",
          zPct %in% 75:90 ~ "High-Average",
          zPct %in% 25:74 ~ "Average",
          zPct %in% 9:24 ~ "Low-Average",
          zPct %in% 2:8 ~ "Below Average",
          zPct < 2 ~ "Exceptionally Low",
          TRUE ~ as.character(range)
        )
      )
    
    # 2. sort hi to lo
    ncog2 <- arrange(ncog2, desc(zMean))
    
    # 3. create tibble with new column with domain name lowercase
    ncog_level2_status <- tibble(
      name = ncog2$subdomain,
      y = ncog2$zMean,
      y2 = ncog2$zPct,
      range = ncog2$range,
      drilldown = tolower(paste(x_level, name, sep = "_"))
    )
    
    list(
      id = tolower(x_level),
      type = "column",
      data = list_parse(ncog_level2_status)
    )
  })
```

```{r drilldown-level3}
## Level 3
## Narrow subdomains
## reuse function
ncog_level3_drill <-
  lapply(unique(neurocog$domain), function(x_level) {
    ncog2 <- subset(neurocog, neurocog$domain %in% x_level)
    
    # reuse function but with y_level
    lapply(unique(ncog2$subdomain), function(y_level) {
      # 1. create mean z-scores for subdomain
      # ncog3 becomes pronoun for domain
      ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
      
      ncog3 <- ncog3 %>%
        group_by(narrow) %>%
        summarize(zMean = mean(z), zPct = mean(percentile)) %>%
        mutate(range = NA)
      
      # round z-score to 1 decimal
      ncog3$zMean <- round(ncog3$zMean, 2L)
      ncog3$zPct <- round(ncog3$zPct, 0L)
      ncog3 <-
        ncog3 %>%
        dplyr::mutate(
          range = dplyr::case_when(
            zPct >= 98 ~ "Exceptionally High",
            zPct %in% 91:97 ~ "Above Average",
            zPct %in% 75:90 ~ "High-Average",
            zPct %in% 25:74 ~ "Average",
            zPct %in% 9:24 ~ "Low-Average",
            zPct %in% 2:8 ~ "Below Average",
            zPct < 2 ~ "Exceptionally Low",
            TRUE ~ as.character(range)
          )
        )
      
      ncog3 <- arrange(ncog3, desc(zMean))
      
      ncog_level3_status <- tibble(
        name = ncog3$narrow,
        y = ncog3$zMean,
        y2 = ncog3$zPct,
        range = ncog3$range,
        drilldown = tolower(paste(x_level, y_level, name, sep = "_"))
      )
      
      list(
        id = tolower(paste(x_level, y_level, sep = "_")),
        type = "column",
        data = list_parse(ncog_level3_status)
      )
    })
  }) %>% unlist(recursive = FALSE)
```

```{r drilldown-level4}
## Level 4
## Scale scores
## reuse both functions
ncog_level4_drill <-
  lapply(unique(neurocog$domain), function(x_level) {
    ncog2 <- subset(neurocog, neurocog$domain %in% x_level)
    
    lapply(unique(ncog2$subdomain), function(y_level) {
      ncog3 <- subset(ncog2, ncog2$subdomain %in% y_level)
      
      lapply(unique(ncog3$narrow), function(z_level) {
        ncog4 <- subset(ncog3, ncog3$narrow %in% z_level)
        
        ncog4 <-
          ncog4 %>%
          group_by(scale) %>%
          summarize(zMean = mean(z),
                    zPct = mean(percentile)) %>%
          mutate(range = NA)
        
        # round z-score to 1 decimal
        ncog4$zMean <- round(ncog4$zMean, 2L)
        ncog4$zPct <- round(ncog4$zPct, 0L)
        ncog4 <-
          ncog4 %>%
          dplyr::mutate(
            range = dplyr::case_when(
              zPct >= 98 ~ "Exceptionally High",
              zPct %in% 91:97 ~ "Above Average",
              zPct %in% 75:90 ~ "High-Average",
              zPct %in% 25:74 ~ "Average",
              zPct %in% 9:24 ~ "Low-Average",
              zPct %in% 2:8 ~ "Below Average",
              zPct < 2 ~ "Exceptionally Low",
              TRUE ~ as.character(range)
            )
          )
        
        ncog4 <- arrange(ncog4, desc(zMean))
        
        ncog_level4_status <- tibble(
          name = ncog4$scale,
          y = ncog4$zMean,
          y2 = ncog4$zPct,
          range = ncog4$range
        )
        
        list(
          id = tolower(paste(x_level, y_level, z_level, sep = "_")),
          type = "column",
          data = list_parse(ncog_level4_status)
        )
      })
    }) %>% unlist(recursive = FALSE)
  }) %>% unlist(recursive = FALSE)
```


```{r}
thm_merge <- hc_theme_merge(
  hc_theme_monokai(),
  hc_theme_darkunica()
)
```

```{r drilldown-plot, fig.cap='Highchart`R` Drilldown on Cognitive Scores', fig.width=12, fig.height=8, fig.retina=3, out.width = "100%"}
# Tooltip
x <- c("Name", "Score", "Percentile", "Range")
y <- c("{point.name}", "{point.y}", "{point.y2}", "{point.range}")
tt <- tooltip_table(x, y)

## Create drilldown bar plot zscores
plot1 <-
  highchart() %>%
  hc_title(
    text = patient,
    style = list(
      fontSize = "15px")) %>%
  hc_add_series(
    ncog_level1_status,
    type = "bar",
    name = "Neuropsychological Test Scores",
    hcaes(x = name, y = y)) %>%
  hc_xAxis(
    type = "category",
    title = list(
      text = "Domain"),
    categories = .$name) %>%
  hc_yAxis(
    title = list(
      text = "Z-Score (M = 0, SD = 1)"),
    labels = list(
      format = "{value}")) %>%
  hc_tooltip(
    pointFormat = tt,
    useHTML = TRUE,
    valueDecimals = 1) %>%
  hc_plotOptions(
    series = list(
      colorByPoint = TRUE,
      allowPointSelect = TRUE,
      dataLabels = TRUE)) %>%
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series = c(
      ncog_level2_drill,
      ncog_level3_drill,
      ncog_level4_drill)) %>%
  hc_colorAxis(
    minColor = "red",
    maxColor = "blue") %>%
  hc_add_theme(
    thm_merge) %>% 
  hc_chart(
    style = list(
      fontFamily = "Cabin"),
    backgroundColor = list("gray")
  )
plot1
```







